/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.SocialSimRos
{
    public class PersonEntryArray : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "social_sim_ros/PersonEntryArray";

        //  Message defining an array of all people entries
        public Header header;
        //  Age of the track
        public PersonEntry[] people;
        //  Array containing the entries for the N tracked persons

        public PersonEntryArray()
        {
            this.header = new Header();
            this.people = new PersonEntry[0];
        }

        public PersonEntryArray(Header header, PersonEntry[] people)
        {
            this.header = header;
            this.people = people;
        }
    }
}
