/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.SocialSimRos
{
    public class PersonEntry : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "social_sim_ros/PersonEntry";

        //  Message defining an entry of a person
        public Header header;
        //  Age of the track
        public ulong track_id;
        //  Unique ID for each person
        //  The following fields are extracted from the Kalman state x and its covariance C
        //  Pose of the track
        public Pose pose;
        //  Velocity of the track
        public Twist twist;

        public PersonEntry()
        {
            this.header = new Header();
            this.track_id = 0;
            this.pose = new Pose();
            this.twist = new Twist();
        }

        public PersonEntry(Header header, ulong track_id, Pose pose, Twist twist)
        {
            this.header = header;
            this.track_id = track_id;
            this.pose = pose;
            this.twist = twist;
        }
    }
}
