/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.SocialSimRos
{
    public class PoseArray : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "social_sim_ros/PoseArray";

        //  Message containing an array of possible robot spawn positions and target positions
        public Pose[] positions;
        //  Array of Pose messages

        public PoseArray()
        {
            this.positions = new Pose[0];
        }

        public PoseArray(Pose[] positions)
        {
            this.positions = positions;
        }
    }
}
