/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.SocialSimRos
{
    public class TrialStart : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "social_sim_ros/TrialStart";

        //  Message containing the parameters to start an A-B navigation trial
        public Header header;
        public string trial_name;
        //  Which trial name are we running
        public ushort trial_number;
        //  Which trial number are we running
        public Pose spawn;
        //  Robot spawn position
        public Pose target;
        //  Robot target position
        public uint num_peds;
        //  Number of pedestrians to spawn
        public double time_limit;
        //  Time limit for the trial (in seconds)

        public TrialStart()
        {
            this.header = new Header();
            this.trial_name = "";
            this.trial_number = 0;
            this.spawn = new Pose();
            this.target = new Pose();
            this.num_peds = 0;
            this.time_limit = 0.0;
        }

        public TrialStart(Header header, string trial_name, ushort trial_number, Pose spawn, Pose target, uint num_peds, double time_limit)
        {
            this.header = header;
            this.trial_name = trial_name;
            this.trial_number = trial_number;
            this.spawn = spawn;
            this.target = target;
            this.num_peds = num_peds;
            this.time_limit = time_limit;
        }
    }
}
