//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MGetDirectionResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/GetDirection";

        public Geometry.MVector3 direction;
        public ushort relative_angle;

        public MGetDirectionResponse()
        {
            this.direction = new Geometry.MVector3();
            this.relative_angle = 0;
        }

        public MGetDirectionResponse(Geometry.MVector3 direction, ushort relative_angle)
        {
            this.direction = direction;
            this.relative_angle = relative_angle;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(direction.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.relative_angle));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.direction.Deserialize(data, offset);
            this.relative_angle = BitConverter.ToUInt16(data, offset);
            offset += 2;

            return offset;
        }

        public override string ToString()
        {
            return "MGetDirectionResponse: " +
            "\ndirection: " + direction.ToString() +
            "\nrelative_angle: " + relative_angle.ToString();
        }
    }
}
