//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MGetFieldRequest : Message
    {
        public const string RosMessageName = "gizmo_msgs/GetField";

        public string name;

        public MGetFieldRequest()
        {
            this.name = "";
        }

        public MGetFieldRequest(string name)
        {
            this.name = name;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MGetFieldRequest: " +
            "\nname: " + name.ToString();
        }
    }
}
