//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MGetFieldResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/GetField";

        public string json_value;

        public MGetFieldResponse()
        {
            this.json_value = "";
        }

        public MGetFieldResponse(string json_value)
        {
            this.json_value = json_value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.json_value));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var json_valueStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.json_value = DeserializeString(data, offset, json_valueStringBytesLength);
            offset += json_valueStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MGetFieldResponse: " +
            "\njson_value: " + json_value.ToString();
        }
    }
}
