//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MMqttSubscribeRequest : Message
    {
        public const string RosMessageName = "gizmo_msgs/MqttSubscribe";

        public string topic;

        public MMqttSubscribeRequest()
        {
            this.topic = "";
        }

        public MMqttSubscribeRequest(string topic)
        {
            this.topic = topic;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.topic));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var topicStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.topic = DeserializeString(data, offset, topicStringBytesLength);
            offset += topicStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MMqttSubscribeRequest: " +
            "\ntopic: " + topic.ToString();
        }
    }
}
