//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MPhotoCaptureResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/PhotoCapture";

        public Sensor.MCompressedImage image;

        public MPhotoCaptureResponse()
        {
            this.image = new Sensor.MCompressedImage();
        }

        public MPhotoCaptureResponse(Sensor.MCompressedImage image)
        {
            this.image = image;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(image.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.image.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MPhotoCaptureResponse: " +
            "\nimage: " + image.ToString();
        }
    }
}
