//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MRobotInfoResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/RobotInfo";

        public ushort client_interface_ver;
        public string robot_base_ver;
        public string gizmo_ver;

        public MRobotInfoResponse()
        {
            this.client_interface_ver = 0;
            this.robot_base_ver = "";
            this.gizmo_ver = "";
        }

        public MRobotInfoResponse(ushort client_interface_ver, string robot_base_ver, string gizmo_ver)
        {
            this.client_interface_ver = client_interface_ver;
            this.robot_base_ver = robot_base_ver;
            this.gizmo_ver = gizmo_ver;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.client_interface_ver));
            listOfSerializations.Add(SerializeString(this.robot_base_ver));
            listOfSerializations.Add(SerializeString(this.gizmo_ver));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.client_interface_ver = BitConverter.ToUInt16(data, offset);
            offset += 2;
            var robot_base_verStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.robot_base_ver = DeserializeString(data, offset, robot_base_verStringBytesLength);
            offset += robot_base_verStringBytesLength;
            var gizmo_verStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.gizmo_ver = DeserializeString(data, offset, gizmo_verStringBytesLength);
            offset += gizmo_verStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MRobotInfoResponse: " +
            "\nclient_interface_ver: " + client_interface_ver.ToString() +
            "\nrobot_base_ver: " + robot_base_ver.ToString() +
            "\ngizmo_ver: " + gizmo_ver.ToString();
        }
    }
}
