//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MSetNavModeRequest : Message
    {
        public const string RosMessageName = "gizmo_msgs/SetNavMode";

        public string mode;

        public MSetNavModeRequest()
        {
            this.mode = "";
        }

        public MSetNavModeRequest(string mode)
        {
            this.mode = mode;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.mode));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var modeStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.mode = DeserializeString(data, offset, modeStringBytesLength);
            offset += modeStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MSetNavModeRequest: " +
            "\nmode: " + mode.ToString();
        }
    }
}
