//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MSetFieldRequest : Message
    {
        public const string RosMessageName = "gizmo_msgs/SetField";

        public string name;
        public string json_value;

        public MSetFieldRequest()
        {
            this.name = "";
            this.json_value = "";
        }

        public MSetFieldRequest(string name, string json_value)
        {
            this.name = name;
            this.json_value = json_value;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            listOfSerializations.Add(SerializeString(this.json_value));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            var json_valueStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.json_value = DeserializeString(data, offset, json_valueStringBytesLength);
            offset += json_valueStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MSetFieldRequest: " +
            "\nname: " + name.ToString() +
            "\njson_value: " + json_value.ToString();
        }
    }
}
