//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MStatResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/Stat";

        public string state;
        public string direction;

        public MStatResponse()
        {
            this.state = "";
            this.direction = "";
        }

        public MStatResponse(string state, string direction)
        {
            this.state = state;
            this.direction = direction;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.state));
            listOfSerializations.Add(SerializeString(this.direction));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var stateStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.state = DeserializeString(data, offset, stateStringBytesLength);
            offset += stateStringBytesLength;
            var directionStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.direction = DeserializeString(data, offset, directionStringBytesLength);
            offset += directionStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MStatResponse: " +
            "\nstate: " + state.ToString() +
            "\ndirection: " + direction.ToString();
        }
    }
}
