//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MUploaderStatusResponse : Message
    {
        public const string RosMessageName = "gizmo_msgs/UploaderStatus";

        //  In test environment, we let the cloud uploader pick its own path for the
        //  uploader queue.  In normal operation this will point to
        //  /mayfield/something/something
        public string uploader_queue;

        public MUploaderStatusResponse()
        {
            this.uploader_queue = "";
        }

        public MUploaderStatusResponse(string uploader_queue)
        {
            this.uploader_queue = uploader_queue;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.uploader_queue));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var uploader_queueStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.uploader_queue = DeserializeString(data, offset, uploader_queueStringBytesLength);
            offset += uploader_queueStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MUploaderStatusResponse: " +
            "\nuploader_queue: " + uploader_queue.ToString();
        }
    }
}
