//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.SocialSimRos
{
    public class MPersonEntryArray : Message
    {
        public const string RosMessageName = "social_sim_ros/PersonEntryArray";

        //  Message defining an array of all people entries
        public MHeader header;
        //  Age of the track
        public MPersonEntry[] people;
        //  Array containing the entries for the N tracked persons

        public MPersonEntryArray()
        {
            this.header = new MHeader();
            this.people = new MPersonEntry[0];
        }

        public MPersonEntryArray(MHeader header, MPersonEntry[] people)
        {
            this.header = header;
            this.people = people;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());

            listOfSerializations.Add(BitConverter.GetBytes(people.Length));
            foreach (var entry in people)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);

            var peopleArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.people = new MPersonEntry[peopleArrayLength];
            for (var i = 0; i < peopleArrayLength; i++)
            {
                this.people[i] = new MPersonEntry();
                offset = this.people[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "MPersonEntryArray: " +
            "\nheader: " + header.ToString() +
            "\npeople: " + System.String.Join(", ", people.ToList());
        }
    }
}
