//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MHeadPose : Message
    {
        public const string RosMessageName = "gizmo_msgs/HeadPose";

        public float pan;
        public float tilt;

        public MHeadPose()
        {
            this.pan = 0.0f;
            this.tilt = 0.0f;
        }

        public MHeadPose(float pan, float tilt)
        {
            this.pan = pan;
            this.tilt = tilt;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.pan));
            listOfSerializations.Add(BitConverter.GetBytes(this.tilt));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.pan = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.tilt = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MHeadPose: " +
            "\npan: " + pan.ToString() +
            "\ntilt: " + tilt.ToString();
        }
    }
}
