//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Gizmo
{
    public class MStringStamped : Message
    {
        public const string RosMessageName = "gizmo_msgs/StringStamped";

        public MHeader header;
        public string timems;
        public string data;

        public MStringStamped()
        {
            this.header = new MHeader();
            this.timems = "";
            this.data = "";
        }

        public MStringStamped(MHeader header, string timems, string data)
        {
            this.header = header;
            this.timems = timems;
            this.data = data;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(header.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.timems));
            listOfSerializations.Add(SerializeString(this.data));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.header.Deserialize(data, offset);
            var timemsStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.timems = DeserializeString(data, offset, timemsStringBytesLength);
            offset += timemsStringBytesLength;
            var dataStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.data = DeserializeString(data, offset, dataStringBytesLength);
            offset += dataStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "MStringStamped: " +
            "\nheader: " + header.ToString() +
            "\ntimems: " + timems.ToString() +
            "\ndata: " + data.ToString();
        }
    }
}
