//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Gizmo
{
    public class MVolumeButton : Message
    {
        public const string RosMessageName = "gizmo_msgs/VolumeButton";

        public bool up_button_pressed;
        public bool down_button_pressed;

        public MVolumeButton()
        {
            this.up_button_pressed = false;
            this.down_button_pressed = false;
        }

        public MVolumeButton(bool up_button_pressed, bool down_button_pressed)
        {
            this.up_button_pressed = up_button_pressed;
            this.down_button_pressed = down_button_pressed;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.up_button_pressed));
            listOfSerializations.Add(BitConverter.GetBytes(this.down_button_pressed));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.up_button_pressed = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.down_button_pressed = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "MVolumeButton: " +
            "\nup_button_pressed: " + up_button_pressed.ToString() +
            "\ndown_button_pressed: " + down_button_pressed.ToString();
        }
    }
}
