/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.MoveBase
{
    public class MoveBaseGoal : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "move_base_msgs/MoveBaseGoal";

        public PoseStamped target_pose;

        public MoveBaseGoal()
        {
            this.target_pose = new PoseStamped();
        }

        public MoveBaseGoal(PoseStamped target_pose)
        {
            this.target_pose = target_pose;
        }
    }
}
