/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class AgentForce : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/AgentForce";

        //  Forces acting on an agent.
        //  Basic SFM forces.
        public Vector3 desired_force;
        public Vector3 obstacle_force;
        public Vector3 social_force;
        //  Additional Group Forces
        public Vector3 group_coherence_force;
        public Vector3 group_gaze_force;
        public Vector3 group_repulsion_force;
        //  Extra stabilization/custom forces.
        public Vector3 random_force;

        public AgentForce()
        {
            this.desired_force = new Vector3();
            this.obstacle_force = new Vector3();
            this.social_force = new Vector3();
            this.group_coherence_force = new Vector3();
            this.group_gaze_force = new Vector3();
            this.group_repulsion_force = new Vector3();
            this.random_force = new Vector3();
        }

        public AgentForce(Vector3 desired_force, Vector3 obstacle_force, Vector3 social_force, Vector3 group_coherence_force, Vector3 group_gaze_force, Vector3 group_repulsion_force, Vector3 random_force)
        {
            this.desired_force = desired_force;
            this.obstacle_force = obstacle_force;
            this.social_force = social_force;
            this.group_coherence_force = group_coherence_force;
            this.group_gaze_force = group_gaze_force;
            this.group_repulsion_force = group_repulsion_force;
            this.random_force = random_force;
        }
    }
}
