/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Pedsim;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class AgentState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/AgentState";

        public Header header;
        public ulong id;
        public ushort type;
        public string social_state;
        public Pose pose;
        public Twist twist;
        public AgentForce forces;
        //  Use sensors package to control observability
        //  Social State string constants
        public const string TYPE_STANDING = "standing";
        public const string TYPE_INDIVIDUAL_MOVING = "individual_moving";
        public const string TYPE_WAITING_IN_QUEUE = "waiting_in_queue";
        public const string TYPE_GROUP_MOVING = "group_moving";
        //  Agent types
        //  0, 1 -> ordinary agents
        //  2 -> Robot
        //  3 -> standing/elderly agents

        public AgentState()
        {
            this.header = new Header();
            this.id = 0;
            this.type = 0;
            this.social_state = "";
            this.pose = new Pose();
            this.twist = new Twist();
            this.forces = new AgentForce();
        }

        public AgentState(Header header, ulong id, ushort type, string social_state, Pose pose, Twist twist, AgentForce forces)
        {
            this.header = header;
            this.id = id;
            this.type = type;
            this.social_state = social_state;
            this.pose = pose;
            this.twist = twist;
            this.forces = forces;
        }
    }
}
