/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Pedsim;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class LineObstacles : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/LineObstacles";

        //  A collection of line obstacles.
        //  No need to header since these are detemined at sim initiation time.
        public Header header;
        public LineObstacle[] obstacles;

        public LineObstacles()
        {
            this.header = new Header();
            this.obstacles = new LineObstacle[0];
        }

        public LineObstacles(Header header, LineObstacle[] obstacles)
        {
            this.header = header;
            this.obstacles = obstacles;
        }
    }
}
