/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class LineObstacle : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/LineObstacle";

        //  A line obstacle in the simulator.
        public Point start;
        public Point end;

        public LineObstacle()
        {
            this.start = new Point();
            this.end = new Point();
        }

        public LineObstacle(Point start, Point end)
        {
            this.start = start;
            this.end = end;
        }
    }
}
