/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class SocialRelations : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/SocialRelations";

        public Header header;
        //  All social relations of all tracks in the current time step.
        //  There might be multiple social relations per pair of tracks.
        public SocialRelation[] elements;

        public SocialRelations()
        {
            this.header = new Header();
            this.elements = new SocialRelation[0];
        }

        public SocialRelations(Header header, SocialRelation[] elements)
        {
            this.header = header;
            this.elements = elements;
        }
    }
}
