/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class SocialActivity : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/SocialActivity";

        public string type;
        //  see constants below
        public float confidence;
        //  detection confidence
        public ulong[] track_ids;
        //  IDs of all person tracks involved in the activity, might be one or multiple
        //  Constants for social activity type (just examples at the moment)
        public const string TYPE_SHOPPING = "shopping";
        public const string TYPE_STANDING = "standing";
        public const string TYPE_INDIVIDUAL_MOVING = "individual_moving";
        public const string TYPE_WAITING_IN_QUEUE = "waiting_in_queue";
        public const string TYPE_LOOKING_AT_INFORMATION_SCREEN = "looking_at_information_screen";
        public const string TYPE_LOOKING_AT_KIOSK = "looking_at_kiosk";
        public const string TYPE_GROUP_ASSEMBLING = "group_assembling";
        public const string TYPE_GROUP_MOVING = "group_moving";
        public const string TYPE_FLOW_WITH_ROBOT = "flow";
        public const string TYPE_ANTIFLOW_AGAINST_ROBOT = "antiflow";
        public const string TYPE_WAITING_FOR_OTHERS = "waiting_for_others";
        // string      TYPE_COMMUNICATING = communicating
        // string      TYPE_TAKING_PHOTOGRAPH = taking_photograph
        // string      TYPE_TALKING_ON_PHONE = talking_on_phone

        public SocialActivity()
        {
            this.type = "";
            this.confidence = 0.0f;
            this.track_ids = new ulong[0];
        }

        public SocialActivity(string type, float confidence, ulong[] track_ids)
        {
            this.type = type;
            this.confidence = confidence;
            this.track_ids = track_ids;
        }
    }
}
