/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class SocialRelation : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/SocialRelation";

        public string type;
        //  e.g. mother-son relationship, romantic relationship, etc.
        public float strength;
        //  relationship strength between 0.0 and 1.0
        public uint track1_id;
        public uint track2_id;
        //  Constants for type (just examples at the moment)
        public const string TYPE_SPATIAL = "spatial";
        public const string TYPE_ROMANTIC = "romantic";
        public const string TYPE_PARENT_CHILD = "parent_child";
        public const string TYPE_FRIENDSHIP = "friendship";

        public SocialRelation()
        {
            this.type = "";
            this.strength = 0.0f;
            this.track1_id = 0;
            this.track2_id = 0;
        }

        public SocialRelation(string type, float strength, uint track1_id, uint track2_id)
        {
            this.type = type;
            this.strength = strength;
            this.track1_id = track1_id;
            this.track2_id = track2_id;
        }
    }
}
