/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Pedsim;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class TrackedGroups : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/TrackedGroups";

        //  Message with all currently tracked groups
        // 
        public Header header;
        //  Header containing timestamp etc. of this message
        public TrackedGroup[] groups;
        //  All groups that are currently being tracked

        public TrackedGroups()
        {
            this.header = new Header();
            this.groups = new TrackedGroup[0];
        }

        public TrackedGroups(Header header, TrackedGroup[] groups)
        {
            this.header = header;
            this.groups = groups;
        }
    }
}
