/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Pedsim
{
    public class TrackedPerson : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "pedsim_msgs/TrackedPerson";

        //  Message defining a tracked person
        // 
        public ulong track_id;
        //  unique identifier of the target, consistent over time
        public bool is_occluded;
        //  if the track is currently not observable in a physical way
        public bool is_matched;
        //  if the track is currently matched by a detection
        public ulong detection_id;
        //  id of the corresponding detection in the current cycle (undefined if occluded)
        public Duration age;
        //  age of the track
        //  The following fields are extracted from the Kalman state x and its covariance C
        public PoseWithCovariance pose;
        //  pose of the track (z value and orientation might not be set, check if corresponding variance on diagonal is > 99999)
        public TwistWithCovariance twist;
        //  velocity of the track (z value and rotational velocities might not be set, check if corresponding variance on diagonal is > 99999)

        public TrackedPerson()
        {
            this.track_id = 0;
            this.is_occluded = false;
            this.is_matched = false;
            this.detection_id = 0;
            this.age = new Duration();
            this.pose = new PoseWithCovariance();
            this.twist = new TwistWithCovariance();
        }

        public TrackedPerson(ulong track_id, bool is_occluded, bool is_matched, ulong detection_id, Duration age, PoseWithCovariance pose, TwistWithCovariance twist)
        {
            this.track_id = track_id;
            this.is_occluded = is_occluded;
            this.is_matched = is_matched;
            this.detection_id = detection_id;
            this.age = age;
            this.pose = pose;
            this.twist = twist;
        }
    }
}
